export type QuickSearchLocale = "es" | "en";

export const QUICK_SEARCH_COPY = {
  es: {
    back: "Atrás",
    title: "Búsqueda rápida",
    subtitle: "Encuentra rutas y guarda oportunidades en tu Watchlist.",
    titleRecommendations: "Recomendaciones",
    subtitleRecommendations: "Selecciona países y descubre rutas ordenadas por valor.",
    workspaceHint: "Espacio de busqueda con filtros claros, explicacion del orden y selector por pais.",
    workspaceHintRecommendations: "Selecciona países o aeropuertos y ajusta filtros avanzados si quieres afinar.",
    originLabel: "Origen (IATA)",
    originTip: "Codigo IATA de 3 letras del aeropuerto.",
    originHelp: "Escribe el codigo o usa el selector por pais.",
    iataHelp: "Formato valido: 3 letras (ej: MAD).",
    iataInvalid: "El codigo IATA debe tener 3 letras.",
    originRequired: "Introduce un origen o elige un aeropuerto/pais.",
    destinationRequired: "Introduce un destino o elige un aeropuerto/pais.",
    iataSuggest: "Selecciona una sugerencia para evitar errores de codigo.",
    destinationLabel: "Destino (IATA)",
    destinationTip: "Si hay varias opciones, prueba un aeropuerto alternativo cercano.",
    destinationHelp: "Escribe el codigo o usa el selector por pais.",
    placeholderOrigin: "Ciudad o aeropuerto",
    placeholderDestination: "Ciudad o aeropuerto",
    placeholderDates: "Selecciona fechas",
    pickAirport: "Elegir aeropuerto",
    pickAirportOriginAria: "Elegir aeropuerto de origen",
    pickAirportDestinationAria: "Elegir aeropuerto de destino",
    pickCountryOnly: "Usar todo {country}",
    pickCountryOnlyHint: "Si eliges un país sin aeropuerto, buscaremos en todos sus aeropuertos.",
    countryOnlySelected: "País seleccionado: {country}",
    countryOnlyClear: "Quitar país",
    swapRoute: "Intercambiar ruta",
    swapRouteAria: "Intercambiar origen y destino",
    pickRecent: "Recientes",
    recentAutocompleteLabel: "Recientes guardados",
    removeRecentAirportAria: "Eliminar {iata} de recientes",
    pickSearch: "Buscar aeropuerto o ciudad",
    pickCountrySearch: "Buscar país",
    pickEmpty: "No hay resultados con ese termino.",
    pickClose: "Cerrar",
    flexTitle: "Que margen tienes con la fecha?",
    daysBefore: "Dias antes",
    daysAfter: "Dias despues",
    exactDate: "Fecha exacta",
    flexible: "Flexible",
    flexHelper: "Elige primero una opcion rapida y personaliza solo si te hace falta.",
    flexHelperExact: "Buscaremos justo en la fecha elegida.",
    flexHelperFlexible: "Buscaremos salidas cercanas a tu fecha para encontrar mas opciones.",
    flexHelperCustom: "Ajusta por separado cuantos dias antes y despues quieres explorar.",
    flexPresetExact: "Exacta",
    flexPresetOne: "±1 dia",
    flexPresetTwo: "±2 dias",
    flexPresetThree: "±3 dias",
    flexPresetCustom: "Personalizar",
    flexCustomSummary: "Fecha flexible: {before} dias antes y {after} dias despues",
    flexBeforeControl: "Buscar desde",
    flexAfterControl: "Buscar hasta",
    flexApplyReturn: "Usar este mismo margen tambien para la vuelta",
    dateLabel: "Fecha",
    dateTip: "Elige la fecha exacta de salida.",
    roundTrip: "Ida y vuelta",
    returnLabel: "Vuelta",
    roundTripToggleHint: "Activalo cuando quieras ver ida y vuelta en dos paneles coordinados.",
    roundTripReadyHint: "Tendras ida y vuelta separadas para comparar con calma.",
    passengers: "Pasajeros adultos",
    passengersHint: "Ajusta cuantos adultos viajan. Viru mantendra el contexto en enlaces y ayudas de calendario.",
    passengersBaseFareHint: "La busqueda rapida sigue mostrando precio orientativo base; el numero de adultos si viaja a aperturas y deep-links.",
    passengersStepperDecrease: "Quitar un adulto",
    passengersStepperIncrease: "Anadir un adulto",
    passengersStepperAria: "{count} adultos seleccionados",
    search: "Buscar vuelos",
    searchHintRouteInvalid: "Introduce Origen y Destino validos para buscar",
    searchHintNeedDate: "Selecciona una fecha de salida para buscar",
    searchHintReadyExact: "Viru buscara la ruta exacta con la fecha elegida.",
    searchHintReadyNearby: "Viru tambien mirara aeropuertos cercanos.",
    searchHintLoading: "Viru esta preparando la busqueda.",
    ready: "Listo para buscar",
    searchReadyTitle: "Listo para explorar",
    searchReadyText: "Introduce una ruta y pulsa Buscar vuelos para ver oportunidades.",
    searchReadyHint: "Puedes ampliar con aeropuertos cercanos y +/- dias si no hay resultados.",
    quickLookTitle: "Primer vistazo",
    quickLookBody: "Configura ruta, fecha y filtros, y luego pulsa Buscar vuelos para ver oportunidades.",
    quickLookAcknowledge: "Entendido",
    autocompleteSuggestionsAvailable: "{count} sugerencias disponibles",
    autocompleteNoSuggestions: "No hay sugerencias",
    summaryPassengersSingular: "pasajero",
    summaryPassengersPlural: "pasajeros",
    summaryRoundTrip: "Ida y vuelta",
    summaryRoundTripMissingReturn: "Ida y vuelta (falta vuelta)",
    summaryOneWay: "Solo ida",
    summaryRadius: "aeropuertos cercanos",
    summaryStrictOn: "Solo vuelos que encajan",
    summaryStrictOff: "Con margen flexible",
    summaryDurationMax: "Duracion max",
    summaryDurationOpen: "Sin limite de duracion",
    summaryExclusions: "Exclusiones",
    summaryMissingOrigin: "Falta origen",
    summaryMissingDestination: "Falta destino",
    summaryMissingDate: "Falta fecha",
    searchSummaryTitle: "Resumen de búsqueda",
    quickSummaryTitle: "Tu busqueda",
    summaryRouteExact: "Ruta exacta",
    summaryNearbyOrigin: "Origen cercano",
    summaryNearbyDestination: "Destino cercano",
    summaryDistanceUpTo: "Hasta {km} km",
    summaryExactDateChip: "Fecha exacta",
    summaryFlexChip: "{days} dias",
    summaryFlexCustomChip: "{before} antes / {after} despues",
    summarySeparateFlights: "Vuelos separados",
    summaryIncompleteInfo: "Informacion incompleta",
    summaryAvoids: "Evita {iata}",
    appliedCriteriaTitle: "Criterios aplicados",
    pendingChangesTitle: "Cambios pendientes",
    pendingChangesBody: "Pulsa Buscar vuelos para actualizar resultados.",
    applyAndSearch: "Aplicar y buscar",
    filtersTitle: "Ajustes activos",
    filtersSubtitle: "Revisa como busca Viru y que vuelos te muestra.",
    filtersMicrocopy: "Tip: si no hay resultados, prueba fechas cercanas y aeropuerto cercano.",
    filterConsoleEyebrow: "Ajustes de busqueda",
    filterConsoleTitle: "Ajustes de busqueda",
    filterConsoleSubtitle: "Revisa como busca Viru y que vuelos te muestra.",
    filterConsoleSubtitleExact: "Tienes la busqueda en modo exacto. Puedes ampliarla si lo necesitas.",
    filterConsoleSubtitleFlex: "Viru tambien esta mirando aeropuertos cercanos.",
    filterConsoleToggleOpen: "Ver ajustes",
    filterConsoleToggleClose: "Ocultar ajustes",
    filterCountLabel: "activos",
    filterNoActive: "Sin filtros extra: busqueda directa, horario amplio y resultados completos.",
    filterAppliedOnSearch: "Cambia la busqueda",
    filterAppliedToResults: "Filtros de resultados",
    filterPartialSupport: "Informacion incompleta",
    filterCoverageDirect: "Ruta exacta",
    filterVisibleOpen: "Mostrando todos",
    filterVisibleCustom: "Vista afinada",
    filterExperimentalOn: "Vuelos separados activos",
    filterExperimentalOff: "Vuelos directos primero",
    coverageTitle: "Aeropuertos cercanos",
    coverageBody: "Viru puede mirar solo tu ruta exacta o sumar aeropuertos cercanos cuando quieras abrir el mapa.",
    visibleResultsTitle: "Filtros de resultados",
    visibleResultsBody: "Filtra y ordena los vuelos que Viru ya encontro sin lanzar una nueva busqueda.",
    filterPresetDirect: "Exacta",
    filterPresetDirectHint: "Origen y destino exactos.",
    filterPresetOriginNearby: "Origen flexible",
    filterPresetOriginNearbyHint: "Busca alternativas cerca del origen.",
    filterPresetBothNearby: "Ambos flexibles",
    filterPresetBothNearbyHint: "Explora origen y destino cercanos.",
    filterPresetRegional: "Ampliar al maximo",
    filterPresetRegionalHint: "Activa ambos cercanos y usa radio amplio.",
    resetGroup: "Restablecer grupo",
    appliedPref: "Aplicado desde tus preferencias",
    alternatesTitle: "Alternativos y aeropuertos",
    radiusLabel: "Distancia maxima",
    radiusHint: "Marca aeropuertos cercanos y elige hasta donde puede mirar Viru.",
    radiusInactive: "Activa origenes o destinos cercanos para usar la distancia.",
    priceMin: "Precio minimo",
    priceMax: "Precio maximo",
    nearbyOrigins: "Incluir origenes cercanos",
    nearbyDestinations: "Incluir destinos cercanos",
    timeTitle: "Tiempo y viabilidad",
    timeSubtitle: "Controla franja y duracion total.",
    tripRulesTitle: "Que vuelos te valen",
    tripRulesBody: "Define horarios y flexibilidad para quedarte con vuelos que encajen contigo.",
    departAfter: "Salida desde",
    departBefore: "Salida hasta",
    durationMax: "Duracion maxima (min)",
    strictMode: "Solo mostrar vuelos que encajen",
    strictWarning: "Busqueda flexible: si no hay resultados, Viru puede abrir un poco los horarios para mostrar opciones utiles.",
    stopsTitle: "Vuelos separados",
    stopsSubtitle: "Viru puede combinar tramos separados si dejas tiempo suficiente entre vuelos.",
    includeStops: "Permitir vuelos separados",
    maxStops: "Maximo de escalas",
    bufferMin: "Tiempo minimo entre vuelos",
    bufferMinHint: "Margen recomendado para cambiar de vuelo con calma.",
    excludeOrigins: "Excluir origenes (IATA)",
    excludeDestinations: "Excluir destinos (IATA)",
    selfConnectWarning: "Los vuelos separados no comparten reserva. Revisa siempre el tiempo entre vuelos.",
    resetPrefs: "Restablecer a mis preferencias",
    resetAll: "Limpiar ajustes",
    deepLink: "Abrir vuelo",
    deepLinkAlt: "Copiar parametros",
    deepLinkModalTitle: "Sin enlace directo",
    deepLinkModalBody: "No se pudo generar enlace directo. Copia la busqueda o abre la aerolinea manualmente.",
    deepLinkCopy: "Copiar parametros",
    deepLinkCopied: "Parametros copiados",
    loadingFlight: "cargando vuelo",
    loadingAria: "Cargando",
    loadingTitle: "Buscando vuelos...",
    loadingText: "Probando alternativos y flexibilidad de fechas para encontrar opciones.",
    loadingPhaseRequesting: "Consultando tarifas...",
    loadingPhaseResponseParsed: "Ordenando resultados...",
    loadingPhaseClientDone: "Preparando vista...",
    loadingPhaseCommitted: "Listo",
    loadingSubcheckTitle: "Comprobaciones en curso",
    loadingSubcheckFlight: "Buscando vuelo {route}",
    loadingSubcheckCombo: "Buscando mejor combinacion {index}/{total}",
    loadingSubcheckActive: "en curso",
    loadingSubcheckDone: "completado",
    loadingTotalFlights: "Vuelos a buscar: {count}",
    loadingProgressFlights: "Progreso: {current}/{total} vuelos",
    loadingScope: "Radar activo: {routes} rutas x {days} dias",
    modalOriginCountry: "Pais de origen",
    modalDestinationCountry: "Pais de destino",
    modalPickTitle: "Elegir aeropuerto",
    modalClear: "Borrar seleccion",
    weatherTitle: "Clima previsto",
    weatherSubtitle: "Origen y destino para cada fecha seleccionada",
    weatherOrigin: "Origen",
    weatherDestination: "Destino",
    weatherDepart: "Salida",
    weatherArrive: "Llegada",
    weatherClear: "Despejado",
    weatherMostlyClear: "Poco nuboso",
    weatherCloudy: "Nublado",
    weatherFog: "Niebla",
    weatherDrizzle: "Llovizna",
    weatherRain: "Lluvia",
    weatherSnow: "Nieve",
    weatherShowers: "Chubascos",
    weatherStorm: "Tormenta",
    weatherVariable: "Variable",
    explainTitle: "Como ordenamos",
    explainSubtitle: "Orden inteligente basado en precio, cercania a tu fecha, distancia y ultima comprobacion.",
    explainPriceTitle: "Precio",
    explainTimeTitle: "Desviacion temporal",
    explainAltTitle: "Alternativos",
    explainPrice: "Prioriza oportunidades con mejor valor relativo.",
    explainTime: "Menor distancia a tu fecha objetivo.",
    explainAlt: "Distancia terrestre y facilidad de acceso.",
    disclaimer: "Busqueda rapida con precio orientativo base para 1 adulto, sin extras.",
    disclaimerWatchlistCta: "Guarda en Watchlist para seguir cambios.",
    degraded: "El proveedor no responde ahora mismo. Te mostramos el ultimo dato confirmado.",
    degradedBadge: "Resultados parciales",
    degradedChip: "Ultimo dato confirmado",
    degradedHint: "Si el proveedor no responde, mantenemos el ultimo dato confirmado para que puedas decidir con contexto.",
    filtersRelaxed: "Se relajaron filtros",
    relaxedDateFlexAuto: "flexibilidad de fecha automatica",
    relaxedNearbyAuto: "ampliacion automatica a aeropuertos cercanos",
    relaxedDepartureWindowAuto: "franja horaria ampliada automaticamente",
    results: "resultados",
    orderedBy: "ordenados por",
    moreOptions: "Más opciones",
    orderBy: "Ordenar por",
    paginationShowing: "Mostrando {start}-{end} de {total} resultados",
    paginationPrev: "Anterior",
    paginationNext: "Siguiente",
    toolbarFilters: "Ajustes activos",
    toolbarExplain: "Como ordenamos",
    toolbarCompact: "Vista compacta",
    toolbarExpanded: "Vista detallada",
    toolbarActiveFilters: "Ajustes activos",
    infoSectionTitle: "Informacion",
    viewDetail: "Ver detalle",
    warningDetailsOpen: "Ver detalles",
    warningDetailsClose: "Ocultar detalles",
    warningsGroupedTitle: "Avisos",
    warningProblemTitle: "Problema",
    providerPartialAvailabilityNotice: "Hay resultados confirmados, pero Ryanair no ha devuelto toda la disponibilidad. Actualiza antes de comprar.",
    providerPartialFaresNotice: "Hay resultados confirmados, pero Ryanair no ha devuelto todas las tarifas. Actualiza antes de comprar.",
    providerPartialMixedNotice: "Hay resultados confirmados, pero Ryanair ha respondido solo en parte en esta busqueda.",
    emptyStateMainTitle: "0 resultados con estos filtros",
    emptyStateProviderTitle: "Ryanair no respondio ahora mismo",
    emptyStateProviderPartialTitle: "Busqueda parcial: faltan respuestas de Ryanair",
    emptyShowMore: "Ver más",
    emptyShowLess: "Ver menos",

    rowActionsMoreAria: "Abrir más acciones",
    rowActionsMenuAria: "Acciones adicionales del resultado",
    ariaFiltersToggle: "Ajustes activos ({count})",
    ariaRemoveFilter: "Quitar filtro {value}",
    resultsColRoute: "Ruta",
    resultsColPrice: "Precio",
    resultsColDuration: "Duracion",
    resultsColFreshness: "Ultima comprobacion",
    resultsColActions: "Acciones",
    sortRanking: "Orden recomendado",
    sortPrice: "Precio",
    sortDuration: "Duracion",
    sortFreshness: "Ultima comprobacion",
    sortFreshnessHint: "Comprobado mas recientemente",
    stopsOne: "1 escala",
    stopsTwo: "2 escalas",
    stateIdleKicker: "Panel listo",
    stateLoadingKicker: "Comprobando rutas",
    stateEmptyKicker: "Terminal sin coincidencias",
    stateErrorKicker: "Ruta interrumpida",
    stateRateKicker: "Espera protegida",
    startSearch: "Lanza una busqueda para ver oportunidades.",
    noResultsFilters: "No hay resultados con estos filtros.",
    relaxFilters: "Relajar filtros",
    emptyTitle: "No hay resultados con estos filtros.",
    emptyText: "Prueba a relajar restricciones o ampliar el radio.",
    stateEmptyHint: "Ajusta filtros o usa una accion rapida para recuperar resultados.",
    stateErrorHint: "Revisa los datos del formulario y vuelve a intentarlo.",
    stateRateHint: "Hemos limitado temporalmente la frecuencia para proteger el servicio.",
    emptyCta: "Relajar filtros",
    relaxPreviewTitle: "Cambios propuestos",
    relaxPreviewImpact: "Estos cambios pueden mostrar más resultados.",
    relaxPreviewConfirm: "Aplicar cambios y buscar",
    relaxPreviewCancel: "Cancelar",
    relaxPreviewNoChanges: "No hay cambios propuestos con la configuración actual.",
    emptyLikelyCausesTitle: "Causas probables",
    emptyRelaxActionsTitle: "Prueba rapido",
    emptyCauseStrict: "Viru no esta abriendo margen automaticamente.",
    emptyCauseDuration: "Duracion maxima ajustada puede estar filtrando rutas.",
    emptyCauseTimeWindow: "La franja horaria de salida es estrecha.",
    emptyCauseRadius: "La distancia para aeropuertos cercanos es baja.",
    emptyCauseExclusions: "Hay aeropuertos excluidos que reducen opciones.",
    emptyCauseStops: "No se permiten escalas (solo directos).",
    emptyCauseProvider: "El proveedor no respondio y no pudimos confirmar vuelos ahora mismo.",
    emptyActionDisableStrict: "Permitir mas margen",
    emptyActionIncreaseDuration: "Aumentar duracion +60",
    emptyActionOpenRadius: "Abrir distancia 150 km",
    emptyActionDateFlex: "Usar fechas cercanas (±2)",
    emptyActionClearExclusions: "Limpiar exclusiones",
    emptyActionTryPlus1Day: "Probar ±1 dia",
    emptyActionOpenNearby: "Buscar aeropuertos cercanos",
    emptyActionMaxCoverage: "Ampliar al maximo",
    emptyActionMoreOptions: "Mas opciones",
    relaxToastPrefix: "Relajamos:",
    undoAction: "Deshacer",
    errorTitle: "No hemos podido completar la busqueda.",
    errorText: "Puedes reintentar en unos segundos.",
    errorRetry: "Reintentar",
    rateLimitTitle: "Demasiadas busquedas seguidas.",
    rateLimitText: "Espera unos segundos para volver a intentar.",
    rateLimitCountdown: "Podras buscar en",
    alternative: "Alternativo",
    itineraryDirect: "Directo",
    itinerarySelfConnect: "Vuelos separados",
    source: "Fuente",
    sourcesLabel: "Fuentes",
    sourcesDetailTitle: "Detalle de fuentes",
    sourcesDetailAria: "Ver detalle de fuentes de resultados",
    sourceUnknown: "Desconocida",
    save: "Guardar",
    watchAlreadyInList: "Ya añadido",
    refreshPrice: "Actualizar precio",
    refreshPriceLoading: "Actualizando precio...",
    refreshPriceSuccess: "Precio actualizado. Volvemos a consultar esta ruta.",
    refreshPriceNoFlights: "Ahora mismo no hay resultados para esta ruta.",
    refreshPriceProviderError: "Proveedor sin respuesta. Conservamos la ultima señal.",
    refreshPriceRateLimited: "Demasiadas consultas seguidas. Reintentamos luego.",
    refreshPriceError: "No se pudo actualizar el precio.",
    viewWatchlist: "Ver Watchlist",
    watchExists: "Ya estaba en Watchlist",
    stale: "dato desactualizado",
    lastData: "Ultimo dato",
    score: "Valoracion Viru",
    scoreHint: "Resume precio, fecha, distancia y ultima comprobacion.",
    freshnessLabel: "Comprobado hace",
    freshnessStale: "Ultimo dato confirmado",
    freshnessUnknown: "Todavia no sabemos cuando se comprobo por ultima vez",
    freshnessUnavailableGlobal: "Ultima comprobacion no disponible",
    freshnessUnavailableTooltip: "Esta respuesta no incluyo la hora de la ultima comprobacion.",
    detailsToggle: "Detalles",
    detailsHide: "Ocultar detalles",
    detailsLegs: "Tramos",
    detailsScore: "Por que aparece arriba",
    detailsWindow: "Ventanas horarias",
    detailsAlt: "Alternativos y distancia",
    detailsBuffer: "Tiempo entre vuelos",
    detailsNote: "Viru prioriza precio, tiempo y ultima comprobacion para ayudarte a decidir antes.",
    aiPreferredPrice: "Mejor opcion encontrada",
    aiPreferredAria: "Resultado preferido por IA",
    aiPreferredReasonLabel: "Por que lo recomendamos",
    selectOutbound: "Selecciona una fecha de ida",
    selectReturn: "Selecciona una fecha de vuelta",
    selectReturnHint: "Selecciona una fecha de vuelta para completar ida y vuelta",
    returnBefore: "La fecha de vuelta no puede ser anterior a la ida",
    returnResetAfterOutboundChange: "Hemos limpiado la vuelta para que puedas elegir una nueva fecha coherente.",
    weatherError: "No se pudo cargar el clima para todas las fechas.",
    weatherUnavailableRange: "Clima no disponible para las fechas seleccionadas.",

    searchFailed: "No se pudo buscar.",
    noFlights: "No hay vuelos disponibles para esa fecha.",
    watchAdded: "Guardado en Watchlist",
    watchFailed: "No se pudo guardar",
    deepLinkError: "No se pudo generar el deep-link automatico.",
    noResults: "Sin resultados.",
    truncated: "Resultados truncados para mantener la busqueda rapida.",

    // ── Dual‑panel (ida + vuelta) ──
    sideOutbound: "Ida",
    sideReturn: "Vuelta",
    sideOutboundLabel: "Resultados de ida",
    sideReturnLabel: "Resultados de vuelta",
    sideOutboundRoute: "{origin} → {destination}",
    sideReturnRoute: "{origin} → {destination}",
    combinedPrice: "Precio combinado estimado",
    saveCombination: "Guardar combinación",
    syncPages: "Sincronizar páginas",
    independentFilters: "Filtros independientes",
    sideViewControlsOutboundTitle: "Vista de ida",
    sideViewControlsReturnTitle: "Vista de vuelta",
    sideViewControlsSubtitle: "Estos filtros solo cambian este panel.",
    outboundProgress: "Progreso ida",
    returnProgress: "Progreso vuelta",
    noReturnResults: "Sin resultados de vuelta",
    savingCombination: "Guardando...",
    combinationSaved: "Combinación guardada",
    combinationError: "No se pudo guardar la combinación",
    combinationPartial: "Solo se guardó una parte",
    combinationSelectBoth: "Selecciona un resultado de ida y otro de vuelta para guardar la combinación",

    warnings: {
      stops_no_disponible_en_modo_rapido: "Las escalas no estan disponibles en la busqueda rapida.",
      origen_no_disponible_en_catalogo: "El origen no tiene catalogo de aeropuertos cercanos.",
      destino_no_disponible_en_catalogo: "El destino no tiene catalogo de aeropuertos cercanos.",
      limite_combinaciones_alternativas: "Se limitaron combinaciones para mantener la busqueda rapida.",
      ryanair_unavailable_parcial: "Algunas combinaciones no pudieron consultarse.",
      ryanair_unavailable_partial: "Algunas combinaciones no pudieron consultarse.",
      ryanair_availability_failed_partial: "No pudimos confirmar toda la disponibilidad de Ryanair; te mostramos solo lo que si respondio.",
      ryanair_fares_failed_partial: "No pudimos confirmar todas las tarifas directas de Ryanair; te mostramos los resultados que si quedaron confirmados.",
      ryanair_availability_failed: "La consulta completa de Ryanair no respondio.",
      ryanair_fares_failed: "La consulta rapida de tarifas de Ryanair no respondio.",
      ryanair_provider_unavailable_total: "Ryanair no respondio y no pudimos confirmar vuelos en este momento.",
    },
  },
  en: {
    back: "Back",
    title: "Quick Search",
    subtitle: "Find routes and save opportunities to your watchlist.",
    titleRecommendations: "Recommendations",
    subtitleRecommendations: "Pick countries and see routes ranked by value.",
    workspaceHint: "Search workspace with filters, explainable ranking, and country picker.",
    workspaceHintRecommendations: "Pick countries or airports and refine with advanced filters if needed.",
    originLabel: "Origin (IATA)",
    originTip: "3-letter IATA airport code.",
    originHelp: "Type the code or use the country picker.",
    iataHelp: "Valid format: 3 letters (e.g. MAD).",
    iataInvalid: "IATA code must be 3 letters.",
    originRequired: "Enter an origin or choose an airport/country.",
    destinationRequired: "Enter a destination or choose an airport/country.",
    iataSuggest: "Pick a suggestion to avoid IATA code errors.",
    destinationLabel: "Destination (IATA)",
    destinationTip: "If there are multiple options, try a nearby alternative.",
    destinationHelp: "Type the code or use the country picker.",
    placeholderOrigin: "City or airport",
    placeholderDestination: "City or airport",
    placeholderDates: "Select dates",
    pickAirport: "Choose airport",
    pickAirportOriginAria: "Choose origin airport",
    pickAirportDestinationAria: "Choose destination airport",
    pickCountryOnly: "Use all {country}",
    pickCountryOnlyHint: "If you choose a country without an airport, we search all airports in that country.",
    countryOnlySelected: "Country selected: {country}",
    countryOnlyClear: "Clear country",
    swapRoute: "Swap route",
    swapRouteAria: "Swap origin and destination",
    pickRecent: "Recent",
    recentAutocompleteLabel: "Recent searches",
    removeRecentAirportAria: "Remove {iata} from recents",
    pickSearch: "Search airport or city",
    pickCountrySearch: "Search country",
    pickEmpty: "No results for that term.",
    pickClose: "Close",
    flexTitle: "How much date flexibility do you have?",
    daysBefore: "Days before",
    daysAfter: "Days after",
    exactDate: "Exact date",
    flexible: "Flexible",
    flexHelper: "Pick a quick option first and fine-tune only if you need it.",
    flexHelperExact: "We will search only on the selected date.",
    flexHelperFlexible: "We will search nearby departure dates to surface more options.",
    flexHelperCustom: "Adjust how many days before and after you want to explore.",
    flexPresetExact: "Exact",
    flexPresetOne: "±1 day",
    flexPresetTwo: "±2 days",
    flexPresetThree: "±3 days",
    flexPresetCustom: "Customize",
    flexCustomSummary: "Custom · -{before} / +{after} days",
    flexBeforeControl: "Search from",
    flexAfterControl: "Search until",
    flexApplyReturn: "Use this same date range for the return",
    dateLabel: "Date",
    dateTip: "Pick the exact departure date.",
    roundTrip: "Round trip",
    returnLabel: "Return",
    roundTripToggleHint: "Turn it on when you want outbound and return in two coordinated panels.",
    roundTripReadyHint: "You will get separate outbound and return panels to compare calmly.",
    passengers: "Adult passengers",
    passengersHint: "Adjust how many adults are traveling. Viru will keep that context in deeplinks and calendar helpers.",
    passengersBaseFareHint: "Quick search still shows an indicative base fare; the adult count does travel into openings and deeplinks.",
    passengersStepperDecrease: "Remove one adult",
    passengersStepperIncrease: "Add one adult",
    passengersStepperAria: "{count} adults selected",
    search: "Search flights",
    searchHintRouteInvalid: "Enter valid Origin and Destination to search",
    searchHintNeedDate: "Select an outbound date to search",
    searchHintReadyExact: "Viru will search the exact route on the selected date.",
    searchHintReadyNearby: "Viru will also check nearby airports.",
    searchHintLoading: "Viru is preparing the search.",
    ready: "Ready to search",
    searchReadyTitle: "Ready to explore",
    searchReadyText: "Enter a route and press Search flights to see opportunities.",
    searchReadyHint: "Expand with nearby airports and +/- days if no results.",
    quickLookTitle: "Quick start",
    quickLookBody: "Set route, dates, and filters, then press Search flights to explore opportunities.",
    quickLookAcknowledge: "Got it",
    autocompleteSuggestionsAvailable: "{count} suggestions available",
    autocompleteNoSuggestions: "No suggestions",
    summaryPassengersSingular: "passenger",
    summaryPassengersPlural: "passengers",
    summaryRoundTrip: "Round trip",
    summaryRoundTripMissingReturn: "Round trip (return missing)",
    summaryOneWay: "One way",
    summaryRadius: "radius",
    summaryStrictOn: "Strict enabled",
    summaryStrictOff: "Strict disabled",
    summaryDurationMax: "Max duration",
    summaryDurationOpen: "Duration open",
    summaryExclusions: "Exclusions",
    summaryMissingOrigin: "Origin missing",
    summaryMissingDestination: "Destination missing",
    summaryMissingDate: "Date missing",
    searchSummaryTitle: "Search summary",
    quickSummaryTitle: "Your search",
    summaryRouteExact: "Exact route",
    summaryNearbyOrigin: "Nearby origin",
    summaryNearbyDestination: "Nearby destination",
    summaryDistanceUpTo: "Up to {km} km",
    summaryExactDateChip: "Exact date",
    summaryFlexChip: "{days} days",
    summaryFlexCustomChip: "{before} before / {after} after",
    summarySeparateFlights: "Separate flights",
    summaryIncompleteInfo: "Incomplete information",
    summaryAvoids: "Avoids {iata}",
    appliedCriteriaTitle: "Applied criteria",
    pendingChangesTitle: "Pending changes",
    pendingChangesBody: "Press Search flights to refresh results.",
    applyAndSearch: "Apply and search",
    filtersTitle: "Active settings",
    filtersSubtitle: "Review how Viru searches and which flights it shows.",
    filtersMicrocopy: "Tip: if empty, try nearby dates and a nearby airport.",
    filterConsoleEyebrow: "Search settings",
    filterConsoleTitle: "Search settings",
    filterConsoleSubtitle: "Review how Viru searches and which flights it shows.",
    filterConsoleSubtitleExact: "Your search is in exact mode. You can widen it if needed.",
    filterConsoleSubtitleFlex: "Viru is also checking nearby airports.",
    filterConsoleToggleOpen: "View settings",
    filterConsoleToggleClose: "Hide settings",
    filterCountLabel: "active",
    filterNoActive: "No extra filters: direct search, broad time window, and complete result view.",
    filterAppliedOnSearch: "Changes the search",
    filterAppliedToResults: "Result filters",
    filterPartialSupport: "Incomplete information",
    filterCoverageDirect: "Exact route",
    filterVisibleOpen: "Showing all",
    filterVisibleCustom: "Tuned view",
    filterExperimentalOn: "Separate flights on",
    filterExperimentalOff: "Direct flights first",
    coverageTitle: "Nearby airports",
    coverageBody: "Viru can check only your exact route or add nearby airports when you want a wider map.",
    visibleResultsTitle: "Result filters",
    visibleResultsBody: "Filter and sort flights Viru already found without starting a new search.",
    filterPresetDirect: "Exact",
    filterPresetDirectHint: "Exact origin and destination.",
    filterPresetOriginNearby: "Flexible origin",
    filterPresetOriginNearbyHint: "Search alternates near the origin.",
    filterPresetBothNearby: "Flexible both",
    filterPresetBothNearbyHint: "Explore nearby origins and destinations.",
    filterPresetRegional: "Expand fully",
    filterPresetRegionalHint: "Enable both nearby sides with a wider radius.",
    resetGroup: "Reset group",
    appliedPref: "Applied from your preferences",
    alternatesTitle: "Alternatives and airports",
    radiusLabel: "Maximum distance",
    radiusHint: "Enable nearby airports and choose how far Viru can look.",
    radiusInactive: "Enable nearby origins or destinations to use distance.",
    priceMin: "Min price",
    priceMax: "Max price",
    nearbyOrigins: "Include nearby origins",
    nearbyDestinations: "Include nearby destinations",
    timeTitle: "Time and viability",
    timeSubtitle: "Control time windows and total duration.",
    tripRulesTitle: "Flights that work for you",
    tripRulesBody: "Define timing and flexibility so Viru keeps flights that fit your trip.",
    departAfter: "Depart after",
    departBefore: "Depart before",
    durationMax: "Max duration (min)",
    strictMode: "Only show flights that fit",
    strictWarning: "Flexible search: Viru can relax time windows if no results are found.",
    stopsTitle: "Separate flights",
    stopsSubtitle: "Viru can combine separate legs if you leave enough time between flights.",
    includeStops: "Allow separate flights",
    maxStops: "Max stops",
    bufferMin: "Minimum time between flights",
    bufferMinHint: "Recommended margin to change flights calmly.",
    excludeOrigins: "Exclude origins (IATA)",
    excludeDestinations: "Exclude destinations (IATA)",
    selfConnectWarning: "Separate flights are not on one booking. Always review the time between flights.",
    resetPrefs: "Reset to my preferences",
    resetAll: "Clear settings",
    deepLink: "Open flight",
    deepLinkAlt: "Copy parameters",
    deepLinkModalTitle: "No direct link",
    deepLinkModalBody: "We could not generate a direct link. Copy the search or open the airline manually.",
    deepLinkCopy: "Copy parameters",
    deepLinkCopied: "Parameters copied",
    loadingFlight: "loading flight",
    loadingAria: "Loading",
    loadingTitle: "Searching opportunities",
    loadingText: "Trying alternatives and flexible dates.",
    loadingPhaseRequesting: "Checking fares...",
    loadingPhaseResponseParsed: "Sorting results...",
    loadingPhaseClientDone: "Preparing view...",
    loadingPhaseCommitted: "Ready",
    loadingSubcheckTitle: "Checks in progress",
    loadingSubcheckFlight: "Searching flight {route}",
    loadingSubcheckCombo: "Searching best combination {index}/{total}",
    loadingSubcheckActive: "in progress",
    loadingSubcheckDone: "done",
    loadingTotalFlights: "Flights to scan: {count}",
    loadingProgressFlights: "Progress: {current}/{total} flights",
    loadingScope: "Live scope: {routes} routes x {days} days",
    modalOriginCountry: "Origin country",
    modalDestinationCountry: "Destination country",
    modalPickTitle: "Choose airport",
    modalClear: "Clear selection",
    weatherTitle: "Weather forecast",
    weatherSubtitle: "Origin and destination for each selected date",
    weatherOrigin: "Origin",
    weatherDestination: "Destination",
    weatherDepart: "Departure",
    weatherArrive: "Arrival",
    weatherClear: "Clear",
    weatherMostlyClear: "Mostly clear",
    weatherCloudy: "Cloudy",
    weatherFog: "Fog",
    weatherDrizzle: "Drizzle",
    weatherRain: "Rain",
    weatherSnow: "Snow",
    weatherShowers: "Showers",
    weatherStorm: "Storm",
    weatherVariable: "Variable",
    explainTitle: "How we rank",
    explainSubtitle: "Heuristic ranking based on price, date deviation, distance, and freshness.",
    explainPriceTitle: "Price",
    explainTimeTitle: "Date deviation",
    explainAltTitle: "Alternatives",
    explainPrice: "Prioritizes opportunities with better relative value.",
    explainTime: "Closer to your target date.",
    explainAlt: "Ground distance and access effort.",
    disclaimer: "Quick search in heuristic mode. Indicative base price for 1 adult without extras.",
    disclaimerWatchlistCta: "Save to watchlist for price changes.",
    degraded: "Provider temporarily unavailable. Showing last confirmed data.",
    degradedBadge: "Degraded mode",
    degradedChip: "Heuristic",
    degradedHint: "If the provider is down, we show the last confirmed data.",
    filtersRelaxed: "Filters relaxed",
    relaxedDateFlexAuto: "automatic date flexibility",
    relaxedNearbyAuto: "automatic nearby-airport expansion",
    relaxedDepartureWindowAuto: "automatically expanded departure window",
    results: "results",
    orderedBy: "sorted by",
    moreOptions: "More options",
    orderBy: "Sort by",
    paginationShowing: "Showing {start}-{end} of {total} results",
    paginationPrev: "Previous",
    paginationNext: "Next",
    toolbarFilters: "Active settings",
    toolbarExplain: "How we rank",
    toolbarCompact: "Compact view",
    toolbarExpanded: "Detailed view",
    toolbarActiveFilters: "Active settings",
    infoSectionTitle: "Information",
    viewDetail: "View detail",
    warningDetailsOpen: "View details",
    warningDetailsClose: "Hide details",
    warningsGroupedTitle: "Warnings",
    warningProblemTitle: "Problem",
    providerPartialAvailabilityNotice: "Showing confirmed results, but some Ryanair availability checks did not respond.",
    providerPartialFaresNotice: "Showing confirmed results, but some Ryanair fare checks did not respond.",
    providerPartialMixedNotice: "Showing confirmed results, but Ryanair only partially responded in this search.",
    emptyStateMainTitle: "0 results with these filters",
    emptyStateProviderTitle: "Ryanair is not responding right now",
    emptyStateProviderPartialTitle: "Partial search: Ryanair did not fully respond",
    emptyShowMore: "Show more",
    emptyShowLess: "Show less",
    rowActionsMoreAria: "Open more actions",
    rowActionsMenuAria: "Additional result actions",
    ariaFiltersToggle: "Active settings ({count})",
    ariaRemoveFilter: "Remove filter {value}",
    resultsColRoute: "Route",
    resultsColPrice: "Price",
    resultsColDuration: "Duration",
    resultsColFreshness: "Freshness",
    resultsColActions: "Actions",
    sortRanking: "Ranking",
    sortPrice: "Price",
    sortDuration: "Duration",
    sortFreshness: "Freshness",
    sortFreshnessHint: "Latest update",
    stopsOne: "1 stop",
    stopsTwo: "2 stops",
    stateIdleKicker: "Panel ready",
    stateLoadingKicker: "Checking routes",
    stateEmptyKicker: "No matches terminal",
    stateErrorKicker: "Route interrupted",
    stateRateKicker: "Protected pause",
    startSearch: "Run a search to see opportunities.",
    noResultsFilters: "No results with these filters.",
    relaxFilters: "Relax filters",
    emptyTitle: "No results with these filters.",
    emptyText: "Try relaxing restrictions or expanding the radius.",
    stateEmptyHint: "Adjust filters or use a quick relax action to recover results.",
    stateErrorHint: "Review form inputs and try again.",
    stateRateHint: "Requests are temporarily limited to protect the service.",
    emptyCta: "Relax filters",
    relaxPreviewTitle: "Proposed changes",
    relaxPreviewImpact: "These changes may show more results.",
    relaxPreviewConfirm: "Apply changes and search",
    relaxPreviewCancel: "Cancel",
    relaxPreviewNoChanges: "No changes are needed with the current settings.",
    emptyLikelyCausesTitle: "Likely causes",
    emptyRelaxActionsTitle: "Quick relax",
    emptyCauseStrict: "Viru is not opening extra margin automatically.",
    emptyCauseDuration: "Max duration may be filtering valid routes.",
    emptyCauseTimeWindow: "The departure time window is narrow.",
    emptyCauseRadius: "Alternate-airport radius is limited.",
    emptyCauseExclusions: "Excluded airports are reducing options.",
    emptyCauseStops: "Stops are disabled (direct only).",
    emptyCauseProvider: "The provider did not respond, so we could not confirm flights right now.",
    emptyActionDisableStrict: "Allow more margin",
    emptyActionIncreaseDuration: "Increase duration +60",
    emptyActionOpenRadius: "Open distance to 150 km",
    emptyActionDateFlex: "Use nearby dates (±2)",
    emptyActionClearExclusions: "Clear exclusions",
    emptyActionTryPlus1Day: "Try ±1 day",
    emptyActionOpenNearby: "Search nearby airports",
    emptyActionMaxCoverage: "Expand fully",
    emptyActionMoreOptions: "More options",
    relaxToastPrefix: "Relaxed:",
    undoAction: "Undo",
    errorTitle: "We couldn't complete the search.",
    errorText: "Try again in a few seconds.",
    errorRetry: "Retry",
    rateLimitTitle: "Too many searches in a row.",
    rateLimitText: "Wait a few seconds before trying again.",
    rateLimitCountdown: "You can search in",
    alternative: "Alternative",
    itineraryDirect: "Direct",
    itinerarySelfConnect: "Separate flights",
    source: "Source",
    sourcesLabel: "Sources",
    sourcesDetailTitle: "Source details",
    sourcesDetailAria: "View source details for results",
    sourceUnknown: "Unknown",
    save: "Save",
    watchAlreadyInList: "Already added",
    refreshPrice: "Refresh price",
    refreshPriceLoading: "Refreshing price...",
    refreshPriceSuccess: "Price revalidated. We are reloading this route.",
    refreshPriceNoFlights: "There are no results for this route right now.",
    refreshPriceProviderError: "Provider unavailable. We kept the last known signal.",
    refreshPriceRateLimited: "Too many refreshes in a row. We will retry later.",
    refreshPriceError: "Price could not be refreshed.",
    viewWatchlist: "View Watchlist",
    watchExists: "Already saved",
    stale: "stale",
    lastData: "Last data",
    score: "Score",
    scoreHint: "Heuristic ranking",
    freshnessLabel: "Updated",
    freshnessStale: "Last known data",
    freshnessUnknown: "No freshness data",
    freshnessUnavailableGlobal: "Freshness unavailable",
    freshnessUnavailableTooltip: "No freshness timestamp was returned in this response.",
    detailsToggle: "Details",
    detailsHide: "Hide details",
    detailsLegs: "Legs",
    detailsScore: "Score breakdown",
    detailsWindow: "Time windows",
    detailsAlt: "Alternatives & distance",
    detailsBuffer: "Time between flights",
    detailsNote: "Heuristic prioritizes price, time, and freshness.",
    aiPreferredPrice: "Recommended price",
    aiPreferredAria: "AI preferred result",
    aiPreferredReasonLabel: "Recommended reason",
    selectOutbound: "Select an outbound date",
    selectReturn: "Select a return date",
    selectReturnHint: "Select a return date to complete round trip",
    returnBefore: "Return date cannot be earlier than outbound",
    returnResetAfterOutboundChange: "We cleared the return so you can pick a date that still fits the outbound.",
    weatherError: "Weather data could not be loaded for all dates.",
    weatherUnavailableRange: "Weather unavailable for the selected dates.",
    searchFailed: "Search failed.",
    noFlights: "No flights available for that date.",
    watchAdded: "Flight added to watchlist",
    watchFailed: "Could not add to watchlist.",
    deepLinkError: "Could not generate the deep-link automatically.",
    noResults: "No results.",
    truncated: "Results were truncated to keep quick search fast.",

    // ── Dual‑panel (outbound + return) ──
    sideOutbound: "Outbound",
    sideReturn: "Return",
    sideOutboundLabel: "Outbound results",
    sideReturnLabel: "Return results",
    sideOutboundRoute: "{origin} → {destination}",
    sideReturnRoute: "{origin} → {destination}",
    combinedPrice: "Estimated combined price",
    saveCombination: "Save combination",
    syncPages: "Sync pages",
    independentFilters: "Independent filters",
    sideViewControlsOutboundTitle: "Outbound view",
    sideViewControlsReturnTitle: "Return view",
    sideViewControlsSubtitle: "These filters only affect this panel.",
    outboundProgress: "Outbound progress",
    returnProgress: "Return progress",
    noReturnResults: "No return results",
    savingCombination: "Saving...",
    combinationSaved: "Combination saved",
    combinationError: "Could not save the combination",
    combinationPartial: "Only partially saved",
    combinationSelectBoth: "Select an outbound and a return result to save the combination",

    warnings: {
      stops_no_disponible_en_modo_rapido: "Stops are not available in quick search.",
      origen_no_disponible_en_catalogo: "Origin has no nearby airport catalog.",
      destino_no_disponible_en_catalogo: "Destination has no nearby airport catalog.",
      limite_combinaciones_alternativas: "Combinations were limited to keep quick search fast.",
      ryanair_unavailable_parcial: "Some combinations could not be queried.",
      ryanair_unavailable_partial: "Some combinations could not be queried.",
      ryanair_availability_failed_partial: "Some Ryanair availability checks failed; showing direct fares that did respond.",
      ryanair_fares_failed_partial: "Some Ryanair fare checks failed; showing results confirmed by availability.",
      ryanair_availability_failed: "Ryanair full availability did not respond.",
      ryanair_fares_failed: "Ryanair fare lookup did not respond.",
      ryanair_provider_unavailable_total: "Ryanair did not respond and we could not confirm flights right now.",
    },
  },
} as const;

type QuickSearchCopyMap = typeof QUICK_SEARCH_COPY.es;
type QuickSearchWarnings = QuickSearchCopyMap["warnings"];
export type QuickSearchCopyKey = Exclude<keyof QuickSearchCopyMap, "warnings">;

export function resolveQuickSearchLocale(raw?: string | null): QuickSearchLocale {
  if (raw && raw.toLowerCase().startsWith("en")) return "en";
  return "es";
}

export function getQuickSearchCopy(raw?: string | null) {
  const locale = resolveQuickSearchLocale(raw);
  const copy = QUICK_SEARCH_COPY[locale];
  const fallback = QUICK_SEARCH_COPY.es;
  const t = (key: QuickSearchCopyKey): string => copy[key] ?? fallback[key] ?? String(key);
  const warnings = copy.warnings as Record<keyof QuickSearchWarnings, string>;
  const fallbackWarnings = fallback.warnings as Record<keyof QuickSearchWarnings, string>;
  const tWarn = (code: string): string => {
    const typedCode = code as keyof QuickSearchWarnings;
    return warnings[typedCode] ?? fallbackWarnings[typedCode] ?? code;
  };
  const localeTag = locale === "en" ? "en-US" : "es-ES";
  return { locale, localeTag, t, tWarn };
}
