import { defineConfig } from "orval";

export default defineConfig({
  viruApi: {
    input: {
      target: "../docs/architecture/openapi.json",
    },
    output: {
      mode: "tags-split",
      target: "./src/api/generated",
      schemas: "./src/api/generated/model",
      client: "react-query",
      mock: false,
      clean: true,
      override: {
        header: () => [
          "// Generated by Orval (v8) — DO NOT EDIT MANUALLY",
          "// Spec: docs/architecture/openapi.json",
          "// Re-generate with: npm run api:generate",
          "",
        ],
        mutator: {
          path: "./src/api/mutator/custom-client.ts",
          name: "customClient",
        },
        query: {
          useQuery: true,
          useInfinite: false,
          useMutation: true,
        },
      },
    },
  },
});

