[mcp_servers.chrome-devtools]
command = "npx"
args = [ "-y", "chrome-devtools-mcp@latest", "--no-usage-statistics", "--isolated" ]

[mcp_servers.serena]
command = "serena"
args = [ "start-mcp-server", "--context", "ide", "--project-from-cwd", "--open-web-dashboard", "false" ]

