"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _app_root_load from './app-root-load.bones.json'
import _public_context_load from './public-context-load.bones.json'
import _landing_session_load from './landing-session-load.bones.json'
import _landing_preview_session_load from './landing-preview-session-load.bones.json'
import _private_module_load from './private-module-load.bones.json'
import _private_summary_load from './private-summary-load.bones.json'
import _watchlist_map_load from './watchlist-map-load.bones.json'
import _auth_guard_load from './auth-guard-load.bones.json'
import _admin_access_load from './admin-access-load.bones.json'
import _admin_product_health_load from './admin-product-health-load.bones.json'
import _hotel_observability_access_load from './hotel-observability-access-load.bones.json'
import _help_page_load from './help-page-load.bones.json'
import _public_route_load from './public-route-load.bones.json'
import _register_session_load from './register-session-load.bones.json'
import _login_session_load from './login-session-load.bones.json'
import _forgot_password_session_load from './forgot-password-session-load.bones.json'
import _preferences_region_load from './preferences-region-load.bones.json'
import _preferences_appearance_load from './preferences-appearance-load.bones.json'
import _preferences_search_load from './preferences-search-load.bones.json'
import _private_list_load from './private-list-load.bones.json'
import _admin_checks_load from './admin-checks-load.bones.json'
import _watchlist_compare_load from './watchlist-compare-load.bones.json'
import _public_topbar_load from './public-topbar-load.bones.json'
import _admin_metrics_load from './admin-metrics-load.bones.json'
import _hotel_observability_load from './hotel-observability-load.bones.json'
import _door_to_door_preferences_load from './door-to-door-preferences-load.bones.json'
import _account_security_activity_load from './account-security-activity-load.bones.json'
import _account_profile_load from './account-profile-load.bones.json'
import _watch_live_flight_load from './watch-live-flight-load.bones.json'
import _watch_detail_history_load from './watch-detail-history-load.bones.json'
import _watchlist_list_load from './watchlist-list-load.bones.json'
import _watch_history_load from './watch-history-load.bones.json'
import _quick_search_progress_load from './quick-search-progress-load.bones.json'
import _door_to_door_results_load from './door-to-door-results-load.bones.json'
import _community_popular_destinations_load from './community-popular-destinations-load.bones.json'
import _community_corridors_load from './community-corridors-load.bones.json'
import _watch_detail_title_load from './watch-detail-title-load.bones.json'
import _navigation_pending_load from './navigation-pending-load.bones.json'

configureBoneyard({"color":"#eee2d1","darkColor":"#27312d","animate":"shimmer","shimmerColor":"#fff8ef","darkShimmerColor":"#36443e","speed":"1.8s","shimmerAngle":112,"stagger":24,"transition":220})

registerBones({
  "app-root-load": _app_root_load,
  "public-context-load": _public_context_load,
  "landing-session-load": _landing_session_load,
  "landing-preview-session-load": _landing_preview_session_load,
  "private-module-load": _private_module_load,
  "private-summary-load": _private_summary_load,
  "watchlist-map-load": _watchlist_map_load,
  "auth-guard-load": _auth_guard_load,
  "admin-access-load": _admin_access_load,
  "admin-product-health-load": _admin_product_health_load,
  "hotel-observability-access-load": _hotel_observability_access_load,
  "help-page-load": _help_page_load,
  "public-route-load": _public_route_load,
  "register-session-load": _register_session_load,
  "login-session-load": _login_session_load,
  "forgot-password-session-load": _forgot_password_session_load,
  "preferences-region-load": _preferences_region_load,
  "preferences-appearance-load": _preferences_appearance_load,
  "preferences-search-load": _preferences_search_load,
  "private-list-load": _private_list_load,
  "admin-checks-load": _admin_checks_load,
  "watchlist-compare-load": _watchlist_compare_load,
  "public-topbar-load": _public_topbar_load,
  "admin-metrics-load": _admin_metrics_load,
  "hotel-observability-load": _hotel_observability_load,
  "door-to-door-preferences-load": _door_to_door_preferences_load,
  "account-security-activity-load": _account_security_activity_load,
  "account-profile-load": _account_profile_load,
  "watch-live-flight-load": _watch_live_flight_load,
  "watch-detail-history-load": _watch_detail_history_load,
  "watchlist-list-load": _watchlist_list_load,
  "watch-history-load": _watch_history_load,
  "quick-search-progress-load": _quick_search_progress_load,
  "door-to-door-results-load": _door_to_door_results_load,
  "community-popular-destinations-load": _community_popular_destinations_load,
  "community-corridors-load": _community_corridors_load,
  "watch-detail-title-load": _watch_detail_title_load,
  "navigation-pending-load": _navigation_pending_load,
})
