"""add missing indexes for quick_search_cache_entry and door_to_door_saved_place

Revision ID: 5f465bd665fa
Revises: 0030
Create Date: 2026-06-10 15:57:08.953836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f465bd665fa'
down_revision: Union[str, None] = '0030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quick_search_cache_entry_expires_at_utc'), 'quick_search_cache_entry', ['expires_at_utc'], unique=False)
    op.create_index(op.f('ix_door_to_door_saved_place_watch_id'), 'door_to_door_saved_place', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_door_to_door_saved_place_watch_id'), table_name='door_to_door_saved_place')
    op.drop_index(op.f('ix_quick_search_cache_entry_expires_at_utc'), table_name='quick_search_cache_entry')
    # ### end Alembic commands ###
